global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    honor_labels: true # Retain labels, as within PushGateway use
    static_configs:
    - targets: ['prometheus:9090', 'pushGateway:9091','peer0.org1.example.com:9000', 'peer0.org2.example.com:9000']

  - job_name: cadvisor
    scrape_interval: 1s
    static_configs:
    - targets: ['cadvisor:8080']
