name: CI (Publish)

on:
  push:
    branches: [ "main" ]

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
#  publish-caliper:
#    uses: ./.github/workflows/publish.yml
#    needs: unit-tests
